Repository Team-DeepGround/deep-ground-server, pull requests merged in 2025-07, with the labels that each got.

#324 [Feature] Security Config에 CORS 설정 추가
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
Labels: feature

#320 [Refacotr] 답변 이미지, 질문 관련 로직 수정
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerDetailDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerUpdateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/entity/Answer.java
  src/main/java/com/samsamhajo/deepground/qna/answer/entity/AnswerMedia.java
  src/main/java/com/samsamhajo/deepground/qna/answer/repository/AnswerMediaRepository.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerMediaService.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
  src/main/java/com/samsamhajo/deepground/qna/question/repository/QuestionMediaRepository.java
  src/main/java/com/samsamhajo/deepground/qna/question/repository/QuestionRepository.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionMediaService.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
Labels: refactor

#317 [Feature] 피드 조회하기, 멤버의 피드 요약 목록 조회하기 구현
  src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
  src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feed/model/FetchFeedSummariesResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feed/model/FetchFeedSummaryResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feed/repository/FeedRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java
Labels: feature

#331 [Feature] EC2 배포 자동화 및 Dockerfile 설정 추가
  .github/workflows/deploy.yml
  Dockerfile
  src/main/resources/application.properties
Labels: feature

#328 [Fix] MongoDB 트랜잭션 적용
  src/main/java/com/samsamhajo/deepground/global/config/MongoConfig.java
Labels: fix

#338 [refactor] 기능 검증하면서 추가 로직 수정
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerEditResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerUpdateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerMediaService.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionUpdateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionMediaController.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
Labels: refactor

#343 [Fix] 소셜 로그인 시 동일 이메일 중복 가입 오류
  src/main/java/com/samsamhajo/deepground/auth/oauth/CustomOAuth2UserService.java
  src/main/java/com/samsamhajo/deepground/auth/oauth/OAuthAttributes.java
  src/main/java/com/samsamhajo/deepground/global/config/MongoConfig.java
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
  src/main/java/com/samsamhajo/deepground/member/entity/Member.java
  src/main/java/com/samsamhajo/deepground/member/entity/Provider.java
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupMyListResponse.java
  src/test/java/com/samsamhajo/deepground/auth/oauth/CustomOAuth2UserServiceTest.java
Labels: bug

#353 [Feature] 이메일 인증, 프로필 조회 관련 코드 수정
  src/main/java/com/samsamhajo/deepground/auth/dto/LoginResponse.java
  src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
  src/main/java/com/samsamhajo/deepground/email/service/EmailService.java
  src/main/java/com/samsamhajo/deepground/friend/Dto/FriendDto.java
  src/main/java/com/samsamhajo/deepground/member/Dto/MemberProfileDto.java
  src/main/java/com/samsamhajo/deepground/member/controller/MemberController.java
  src/main/java/com/samsamhajo/deepground/member/entity/Member.java
  src/main/java/com/samsamhajo/deepground/member/entity/MemberProfile.java
  src/main/java/com/samsamhajo/deepground/member/entity/Role.java
  src/main/java/com/samsamhajo/deepground/member/service/MemberService.java
  src/main/java/com/samsamhajo/deepground/member/utils/MemberUtils.java
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/ParticipantSummaryDto.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupMemberSummary.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupMemberService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
Labels: bug
