Repository Team-DeepGround/deep-ground-server, pull requests merged in 2025-05, with the labels that each got.

#46 [Refactor] 피드 관련 엔티티 연관관계 매핑
  src/main/java/com/samsamhajo/deepground/feed/feed/entity/Feed.java
  src/main/java/com/samsamhajo/deepground/feed/feed/entity/FeedLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedComment.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedCommentLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReply.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/entity/SharedFeed.java
Labels: refactor

#48 [Feature] 알림 엔티티 구현
  src/main/java/com/samsamhajo/deepground/global/BaseDocument.java
  src/main/java/com/samsamhajo/deepground/notification/entity/Notification.java
  src/main/java/com/samsamhajo/deepground/notification/entity/NotificationMessage.java
  src/main/java/com/samsamhajo/deepground/notification/entity/NotificationType.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/ChatMessageNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/FriendRequestNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/NotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyGroupNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyScheduleNotificationData.java
  src/main/resources/application.yml
Labels: feature

#50 [Feature] 채팅 메시지 엔티티 구현
  src/main/java/com/samsamhajo/deepground/chat/entity/ChatMessage.java
  src/main/java/com/samsamhajo/deepground/chat/entity/ChatMessageMedia.java
Labels: feature

#49 [Refactor] friend 엔티티 연관관계 매핑
  README.md
  src/main/java/com/samsamhajo/deepground/friend/entity/Friend.java
  src/main/java/com/samsamhajo/deepground/member/entity/Member.java
Labels: refactor

#53 [Refactor] StudyGroup 관련 엔티티 정적 팩토리 및 연관관계 매핑 리팩토링
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroup.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupComment.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupMember.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupReply.java
Labels: refactor

#47 [Refactor] 캘린더 관련 정적 팩토리 메서드 추가 및 연관관계 매핑
  src/main/java/com/samsamhajo/deepground/calendar/entity/MemberStudySchedule.java
  src/main/java/com/samsamhajo/deepground/calendar/entity/StudySchedule.java
Labels: refactor

#60 [Refactor] 질문, 댓글, 답변 연관관계 생성자 & 매핑
  src/main/java/com/samsamhajo/deepground/qna/answer/entity/Answer.java
  src/main/java/com/samsamhajo/deepground/qna/answer/entity/AnswerLike.java
  src/main/java/com/samsamhajo/deepground/qna/answer/entity/AnswerMedia.java
  src/main/java/com/samsamhajo/deepground/qna/comment/entity/Comment.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/QuestionMedia.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/QuestionTag.java
Labels: refactor

#58 [Refactor] 알림 관련 엔티티에 정적 팩토리 메서드 추가
  src/main/java/com/samsamhajo/deepground/notification/entity/Notification.java
  src/main/java/com/samsamhajo/deepground/notification/entity/NotificationMessage.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/ChatMessageNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/FriendRequestNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/NotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyGroupNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyScheduleNotificationData.java
Labels: refactor

#59 [Refactor] 멤버, 관심사, 기술스택 관련 엔티티 생성자 및 연관관계 매핑
  src/main/java/com/samsamhajo/deepground/interest/entity/Interest.java
  src/main/java/com/samsamhajo/deepground/interest/entity/MemberInterest.java
  src/main/java/com/samsamhajo/deepground/member/entity/Member.java
  src/main/java/com/samsamhajo/deepground/techStack/entity/MemberTechStack.java
  src/main/java/com/samsamhajo/deepground/techStack/entity/TechStack.java
Labels: refactor

#64 [Feature] 응답 표준 정의 및 글로벌 기능 구현
  src/main/java/com/samsamhajo/deepground/global/error/core/BaseException.java
  src/main/java/com/samsamhajo/deepground/global/error/core/ErrorCode.java
  src/main/java/com/samsamhajo/deepground/global/error/core/ErrorResponse.java
  src/main/java/com/samsamhajo/deepground/global/error/handler/GlobalErrorCode.java
  src/main/java/com/samsamhajo/deepground/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/samsamhajo/deepground/global/success/SuccessCode.java
  src/main/java/com/samsamhajo/deepground/global/success/SuccessResponse.java
  src/main/java/com/samsamhajo/deepground/global/utils/GlobalLogger.java
Labels: feature

#65 [Feature] WebSocket & Redis 기본 설정
  build.gradle
  src/main/java/com/samsamhajo/deepground/global/config/RedisConfig.java
  src/main/java/com/samsamhajo/deepground/global/config/WebSocketConfig.java
  src/main/java/com/samsamhajo/deepground/global/config/WebSocketSecurityConfig.java
  src/main/java/com/samsamhajo/deepground/global/message/MessagePublisher.java
  src/main/java/com/samsamhajo/deepground/global/message/SimpMessagePublisher.java
  src/main/resources/application.yml
Labels: feature

#67 [Fix] 스웨거 충돌로 인한 주석 처리
  build.gradle
  src/main/java/com/samsamhajo/deepground/global/config/WebSocketSecurityConfig.java
Labels: fix

#95 [Fix] @EnableJpaAuditing 설정 추가
  src/main/java/com/samsamhajo/deepground/global/config/JpaConfig.java
Labels: fix

#161 [Feature] 회원가입 기능 구현
  build.gradle
  src/main/java/com/samsamhajo/deepground/auth/controller/AuthController.java
  src/main/java/com/samsamhajo/deepground/auth/dto/RegisterRequest.java
  src/main/java/com/samsamhajo/deepground/auth/dto/RegisterResponse.java
  src/main/java/com/samsamhajo/deepground/auth/exception/AuthErrorCode.java
  src/main/java/com/samsamhajo/deepground/auth/exception/AuthException.java
  src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
  src/main/java/com/samsamhajo/deepground/auth/success/AuthSuccessCode.java
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
  src/main/java/com/samsamhajo/deepground/interest/repository/InterestRepository.java
  src/main/java/com/samsamhajo/deepground/interest/repository/MemberInterestRepository.java
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/main/java/com/samsamhajo/deepground/techStack/repository/MemberTechStackRepository.java
  src/main/java/com/samsamhajo/deepground/techStack/repository/TechStackRepository.java
  src/test/java/com/samsamhajo/deepground/auth/service/AuthServiceTest.java
Labels: feature

#131 [Feature] 스터디 그룹 생성 기능 구현
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCreateRequest.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCreateResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupMember.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/success/StudyGroupSuccessCode.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceIntegrationTest.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceTest.java
Labels: feature

#133 [Feature] 스터디 상세 조회 API 구현
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupDetailResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroup.java
  src/main/java/com/samsamhajo/deepground/studyGroup/exception/StudyGroupNotFoundException.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/success/StudyGroupSuccessCode.java
  src/test/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepositoryTest.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceDetailsTest.java
Labels: feature

#160 [Feature] 스터디 일정 등록 기능 구현
  src/main/java/com/samsamhajo/deepground/calendar/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/calendar/controller/StudyScheduleController.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/StudyScheduleRequestDto.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/StudyScheduleResponseDto.java
  src/main/java/com/samsamhajo/deepground/calendar/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/calendar/repository/StudyScheduleRepository.java
  src/main/java/com/samsamhajo/deepground/calendar/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
  src/test/java/com/samsamhajo/deepground/calendar/controller/StudyScheduleControllerTest.java
  src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java
Labels: feature

#163 [Feature] Question 작성 구현
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/QuestionStatus.java
  src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionErrorCode.java
  src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionException.java
  src/main/java/com/samsamhajo/deepground/qna/question/repository/QuestionRepository.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
  src/test/java/com/samsamhajo/deepground/IntegrationTestSupport.java
  src/test/java/com/samsamhajo/deepground/question/QuestionTest.java
Labels: feature

#162 [Feature] 피드 글 작성하기 구현
  build.gradle
  src/main/java/com/samsamhajo/deepground/feed/feed/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
  src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedException.java
  src/main/java/com/samsamhajo/deepground/feed/feed/model/FeedCreateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feed/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feed/repository/FeedRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java
  src/test/java/com/samsamhajo/deepground/feed/feed/controller/FeedControllerTest.java
  src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedServiceTest.java
Labels: feature

#164 [Feature/Fix/Refactor] Media 관련 처리로직 구현
  src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedMediaController.java
  src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feed/model/FeedMediaResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feed/repository/FeedMediaRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
  src/main/java/com/samsamhajo/deepground/media/MediaErrorCode.java
  src/main/java/com/samsamhajo/deepground/media/MediaException.java
  src/main/java/com/samsamhajo/deepground/media/MediaSuccessCode.java
  src/main/java/com/samsamhajo/deepground/media/MediaUtils.java
  src/test/java/com/samsamhajo/deepground/media/MediaErrorCodeTest.java
  src/test/java/com/samsamhajo/deepground/media/MediaExceptionTest.java
  src/test/java/com/samsamhajo/deepground/media/MediaSuccessCodeTest.java
  src/test/java/com/samsamhajo/deepground/media/MediaUtilsTest.java
Labels: feature

#143 [Feature] 친구 요청 목록 기능 구현
  src/main/java/com/samsamhajo/deepground/friend/Dto/FriendDto.java
  src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
  src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendController/FriendRequestTest.java
Labels: feature

#166 [Refactor] Security 관련 Config 수정
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
Labels: refactor

#170 [Refactor] 응답 표준 적용 및 코드 구조 개선
  src/main/java/com/samsamhajo/deepground/friend/Dto/FriendDto.java
  src/main/java/com/samsamhajo/deepground/friend/Dto/FriendRequestDto.java
  src/main/java/com/samsamhajo/deepground/friend/Dto/ResponseDto.java
  src/main/java/com/samsamhajo/deepground/friend/Exception/FriendSuccessCode.java
  src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/main/resources/application.yml
  src/test/java/com/samsamhajo/deepground/Friend/FriendRequestTest.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendRequestTest.java
Labels: refactor

#176 [Refactor] 스케줄 도메인 관련 응답 표준화 리팩토링
  src/main/java/com/samsamhajo/deepground/calendar/controller/StudyScheduleController.java
  src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleErrorCode.java
  src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleException.java
  src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleSuccessCode.java
  src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
  src/test/java/com/samsamhajo/deepground/calendar/controller/StudyScheduleControllerTest.java
  src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java
Labels: refactor

#175 [Refactor] Q&A 응답표준 코드 리팩토링
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
  src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionSuccessCode.java
  src/test/java/com/samsamhajo/deepground/question/QuestionTest.java
Labels: refactor

#171 [Feature] 받은 친구 요청 목록 조회 기능 구현
  src/main/java/com/samsamhajo/deepground/friend/Dto/FriendDto.java
  src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
  src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendReceiveTest.java
Labels: feature

#179 [Feature] 프로필에서 친구 요청 기능 구현
  src/main/java/com/samsamhajo/deepground/friend/Exception/FriendErrorCode.java
  src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendRequestTest.java
Labels: feature

#174 [Feature] 친구 요청 수락 기능 구현
  src/main/java/com/samsamhajo/deepground/friend/Exception/FriendErrorCode.java
  src/main/java/com/samsamhajo/deepground/friend/Exception/FriendSuccessCode.java
  src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
  src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/main/java/com/samsamhajo/deepground/member/exception/MemberErrorCode.java
  src/main/java/com/samsamhajo/deepground/member/exception/MemberException.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendReceiveTest.java
Labels: feature

#177 [Feature] 스터디 그룹 참가 요청 기능 구현
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupJoinService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/success/StudyGroupSuccessCode.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupJoinServiceTest.java
Labels: feature

#182 [Feature] 스터디 그룹 댓글 작성 기능 구현
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupCommentController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCommentRequest.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCommentResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupCommentRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupCommentService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/success/StudyGroupSuccessCode.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupCommentServiceTest.java
Labels: feature

#180 [Feature] 스터디 일정 조회 기능 구현
  src/main/java/com/samsamhajo/deepground/calendar/controller/StudyScheduleController.java
  src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleErrorCode.java
  src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleSuccessCode.java
  src/main/java/com/samsamhajo/deepground/calendar/repository/StudyScheduleRepository.java
  src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
  src/test/java/com/samsamhajo/deepground/calendar/controller/StudyScheduleControllerTest.java
  src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java
Labels: feature

#178 [Feature] 친구 요청 거절 기능 구현
  src/main/java/com/samsamhajo/deepground/friend/Exception/FriendSuccessCode.java
  src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/main/java/com/samsamhajo/deepground/member/exception/MemberException.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendReceiveTest.java
Labels: feature

#183 [Feature] 질문 수정 기능 구현
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionUpdateDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
  src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionErrorCode.java
  src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/question/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/question/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
  src/test/java/com/samsamhajo/deepground/question/QuestionTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionUpdateTest.java
Labels: feature

#184 [Feature] 질문 삭제 기능 구현
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
  src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
  src/test/java/com/samsamhajo/deepground/question/QuestionDeleteTest.java
Labels: feature

#189 [Feature] 질문 답변 작성 기능 구현
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerErrorCode.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerException.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/answer/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/answer/repository/AnswerRepository.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
  src/test/java/com/samsamhajo/deepground/question/AnswerTest.java
Labels: feature

#190 [Feature] 이메일 인증 코드 전송 및 검증 기능 구현
  src/main/java/com/samsamhajo/deepground/email/controller/EmailController.java
  src/main/java/com/samsamhajo/deepground/email/dto/EmailRequest.java
  src/main/java/com/samsamhajo/deepground/email/dto/EmailResponse.java
  src/main/java/com/samsamhajo/deepground/email/dto/EmailVerifyRequest.java
  src/main/java/com/samsamhajo/deepground/email/exception/EmailErrorCode.java
  src/main/java/com/samsamhajo/deepground/email/exception/EmailException.java
  src/main/java/com/samsamhajo/deepground/email/repository/EmailVerificationRepository.java
  src/main/java/com/samsamhajo/deepground/email/service/EmailService.java
  src/main/java/com/samsamhajo/deepground/email/success/EmailSuccessCode.java
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/main/resources/application.yml
  src/test/java/com/samsamhajo/deepground/email/service/EmailServiceTest.java
Labels: feature

#181 [Feature] 피드 글 목록 조회
  src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
  src/main/java/com/samsamhajo/deepground/feed/feed/model/FeedListResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feed/model/FeedResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java
  src/main/java/com/samsamhajo/deepground/utils/.gitkeep
  src/test/java/com/samsamhajo/deepground/feed/feed/controller/FeedControllerTest.java
  src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedServiceTest.java
Labels: feature

#191 [Feature] 알림 전송 기능 구현
  src/main/java/com/samsamhajo/deepground/notification/dto/NotificationResponse.java
  src/main/java/com/samsamhajo/deepground/notification/entity/Notification.java
  src/main/java/com/samsamhajo/deepground/notification/entity/NotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/NotificationMessage.java
  src/main/java/com/samsamhajo/deepground/notification/entity/NotificationType.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/ChatMessageNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/FriendNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/FriendRequestNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/NotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/ScheduleNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyGroupNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/entity/data/StudyScheduleNotificationData.java
  src/main/java/com/samsamhajo/deepground/notification/repository/NotificationDataRepository.java
  src/main/java/com/samsamhajo/deepground/notification/repository/NotificationRepository.java
  src/main/java/com/samsamhajo/deepground/notification/service/NotificationService.java
  src/test/java/com/samsamhajo/deepground/notification/service/NotificationServiceTest.java
Labels: feature

#194 [Refactor] Q&A 에러부분 코드 리팩토링
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
  src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
  src/test/java/com/samsamhajo/deepground/question/AnswerTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionDeleteTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionTest.java
Labels: refactor

#198 [Refactor] 캘린더 도메인 리팩토링 및 MemberStudySchedule 파일 추가
  src/main/java/com/samsamhajo/deepground/calendar/controller/MemberStudyScheduleController.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/MemberStudyScheduleRequestDto.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/MemberStudyScheduleResponseDto.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/StudyScheduleResponseDto.java
  src/main/java/com/samsamhajo/deepground/calendar/repository/MemberStudyScheduleRepository.java
  src/main/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleService.java
  src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
  src/test/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleServiceTest.java
  src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java
Labels: refactor

#201 [ Feature ] 친구 목록 조회 기능 구현
  src/main/java/com/samsamhajo/deepground/friend/Exception/FriendSuccessCode.java
  src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
  src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendsTest.java
Labels: feature

#213 [Feature] 특정 멤버의 전체 일정 조회 API 구현
  src/main/java/com/samsamhajo/deepground/calendar/controller/MemberStudyScheduleController.java
  src/main/java/com/samsamhajo/deepground/calendar/dto/MemberScheduleCalendarResponseDto.java
  src/main/java/com/samsamhajo/deepground/calendar/exception/ScheduleErrorCode.java
  src/main/java/com/samsamhajo/deepground/calendar/repository/MemberStudyScheduleRepository.java
  src/main/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleService.java
  src/test/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleServiceTest.java
Labels: feature

#195 [Feature] AccessToken 재발급 기능 구현
  src/main/java/com/samsamhajo/deepground/auth/controller/AuthController.java
  src/main/java/com/samsamhajo/deepground/auth/dto/TokenRefreshRequest.java
  src/main/java/com/samsamhajo/deepground/auth/dto/TokenRefreshResponse.java
  src/main/java/com/samsamhajo/deepground/auth/exception/AuthErrorCode.java
  src/main/java/com/samsamhajo/deepground/auth/jwt/JwtProvider.java
  src/main/java/com/samsamhajo/deepground/auth/repository/RefreshTokenRepository.java
  src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
  src/main/java/com/samsamhajo/deepground/auth/success/AuthSuccessCode.java
  src/test/java/com/samsamhajo/deepground/auth/service/AuthServiceTest.java
  src/test/java/com/samsamhajo/deepground/auth/service/RefreshAccessTokenTest.java
Labels: feature

#212 [Feature] 비밀번호 재설정 기능 구현
  src/main/java/com/samsamhajo/deepground/auth/controller/AuthController.java
  src/main/java/com/samsamhajo/deepground/auth/dto/PasswordResetEmailResponse.java
  src/main/java/com/samsamhajo/deepground/auth/dto/PasswordResetRequest.java
  src/main/java/com/samsamhajo/deepground/auth/dto/PasswordResetResponse.java
  src/main/java/com/samsamhajo/deepground/auth/dto/PasswordResetVerifyRequest.java
  src/main/java/com/samsamhajo/deepground/auth/exception/AuthErrorCode.java
  src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
  src/main/java/com/samsamhajo/deepground/auth/success/AuthSuccessCode.java
  src/main/java/com/samsamhajo/deepground/member/entity/Member.java
  src/test/java/com/samsamhajo/deepground/auth/service/AuthServiceTest.java
  src/test/java/com/samsamhajo/deepground/auth/service/PasswordResetTest.java
Labels: feature

#204 [Feature] 내가 생성한 스터디 목록 조회 기능 구현
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupMyListResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceMyListTest.java
Labels: feature

#205 [Feature] 내가 참여 중인 스터디 그룹 목록 조회 기능 구현
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupParticipationResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupParticipationServiceTest.java
Labels: feature

#199 [Feature] WebSocket 연결 시 JWT 기반 인증
  src/main/java/com/samsamhajo/deepground/auth/jwt/WebSocketInterceptor.java
  src/main/java/com/samsamhajo/deepground/chat/controller/ChatMessageController.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatMessageRequest.java
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
  src/main/java/com/samsamhajo/deepground/global/config/WebSocketConfig.java
  src/main/java/com/samsamhajo/deepground/global/config/WebSocketSecurityConfig.java
  src/main/java/com/samsamhajo/deepground/utils/destination/DestinationUtils.java
  src/test/java/com/samsamhajo/deepground/chat/service/ChatMessageServiceTest.java
  src/test/java/com/samsamhajo/deepground/utils/destination/DestinationUtilsTest.java
Labels: feature

#216 [Feature] 알림 목록 조회 기능 구현
  src/main/java/com/samsamhajo/deepground/notification/controller/NotificationController.java
  src/main/java/com/samsamhajo/deepground/notification/dto/NotificationListRequest.java
  src/main/java/com/samsamhajo/deepground/notification/dto/NotificationListResponse.java
  src/main/java/com/samsamhajo/deepground/notification/repository/NotificationCustomRepository.java
  src/main/java/com/samsamhajo/deepground/notification/repository/NotificationCustomRepositoryImpl.java
  src/main/java/com/samsamhajo/deepground/notification/repository/NotificationRepository.java
  src/main/java/com/samsamhajo/deepground/notification/service/NotificationService.java
  src/main/java/com/samsamhajo/deepground/notification/success/NotificationSuccessCode.java
  src/test/java/com/samsamhajo/deepground/notification/service/NotificationServiceTest.java
Labels: feature

#208 [Feature] 피드 글 삭제하기
  src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
  src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java
  src/main/java/com/samsamhajo/deepground/media/MediaErrorCode.java
  src/main/java/com/samsamhajo/deepground/media/MediaUtils.java
  src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedServiceTest.java
  src/test/java/com/samsamhajo/deepground/media/MediaUtilsTest.java
Labels: feature

#211 [Feature] Answer 수정 로직 구현
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerUpdateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerUpdateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/entity/Answer.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerErrorCode.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
  src/test/java/com/samsamhajo/deepground/question/AnswerUpdateTest.java
Labels: feature

#215 [Feature] 답변 삭제 로직 구현
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
  src/main/java/com/samsamhajo/deepground/qna/answer/entity/Answer.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerErrorCode.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
  src/test/java/com/samsamhajo/deepground/question/AnswerDeleteTest.java
Labels: feature
