Repository Team-DeepGround/deep-ground-server, pull requests merged in 2025-08, with the labels that each got.

#355 [Fix] 테스트 의존성 문제 수정
  build.gradle
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroup.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendReceiveTest.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendRequestTest.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendsTest.java
  src/test/java/com/samsamhajo/deepground/IntegrationTestSupport.java
  src/test/java/com/samsamhajo/deepground/auth/service/AuthServiceTest.java
  src/test/java/com/samsamhajo/deepground/auth/service/LogoutTest.java
  src/test/java/com/samsamhajo/deepground/auth/service/PasswordResetTest.java
  src/test/java/com/samsamhajo/deepground/auth/service/RefreshAccessTokenTest.java
  src/test/java/com/samsamhajo/deepground/email/service/EmailServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedshared/service/SharedFeedServiceTest.java
  src/test/java/com/samsamhajo/deepground/member/service/ProfileTest.java
  src/test/java/com/samsamhajo/deepground/question/AnswerDeleteTest.java
  src/test/java/com/samsamhajo/deepground/question/AnswerLikeTest.java
  src/test/java/com/samsamhajo/deepground/question/AnswerMediaTest.java
  src/test/java/com/samsamhajo/deepground/question/AnswerTest.java
  src/test/java/com/samsamhajo/deepground/question/AnswerUpdateTest.java
  src/test/java/com/samsamhajo/deepground/question/CommentDeleteTest.java
  src/test/java/com/samsamhajo/deepground/question/CommentTest.java
  src/test/java/com/samsamhajo/deepground/question/CommentUpdateTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionDeleteTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionMediaTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionStatusTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionUpdateTest.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupInviteServiceTest.java
  src/test/java/com/samsamhajo/deepground/support/TestMailConfig.java
  src/test/java/com/samsamhajo/deepground/support/TestRedisConfig.java
  src/test/resources/application.yml
Labels: fix

#357 [Fix] 프로필 테스트 코드 오류 해결
  .github/reviewers.yml
  .github/workflows/deploy.yml
  src/test/java/com/samsamhajo/deepground/member/service/ProfileTest.java
Labels: bug

#362 [Feature] 관리자 기능 및 신고 관련 기능 추가
  build.gradle
  src/main/java/com/samsamhajo/deepground/admin/controller/AdminController.java
  src/main/java/com/samsamhajo/deepground/admin/controller/AdminReportController.java
  src/main/java/com/samsamhajo/deepground/admin/dto/AdminDashboardStatsResponse.java
  src/main/java/com/samsamhajo/deepground/admin/exception/AdminErrorCode.java
  src/main/java/com/samsamhajo/deepground/admin/exception/AdminException.java
  src/main/java/com/samsamhajo/deepground/admin/repository/AdminDashboardRepository.java
  src/main/java/com/samsamhajo/deepground/admin/repository/AdminDashboardRepositoryImpl.java
  src/main/java/com/samsamhajo/deepground/admin/repository/AdminReportRepository.java
  src/main/java/com/samsamhajo/deepground/admin/service/AdminReportService.java
  src/main/java/com/samsamhajo/deepground/admin/service/AdminService.java
  src/main/java/com/samsamhajo/deepground/admin/success/AdminSuccessCode.java
  src/main/java/com/samsamhajo/deepground/auth/exception/AuthErrorCode.java
  src/main/java/com/samsamhajo/deepground/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/samsamhajo/deepground/auth/jwt/JwtProvider.java
  src/main/java/com/samsamhajo/deepground/auth/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
  src/main/java/com/samsamhajo/deepground/global/config/AIConfig.java
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
  src/main/java/com/samsamhajo/deepground/member/entity/Member.java
  src/main/java/com/samsamhajo/deepground/member/exception/MemberErrorCode.java
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/main/java/com/samsamhajo/deepground/report/controller/ReportController.java
  src/main/java/com/samsamhajo/deepground/report/dto/AIReportResponse.java
  src/main/java/com/samsamhajo/deepground/report/dto/ReportDetailResponse.java
  src/main/java/com/samsamhajo/deepground/report/dto/ReportRequest.java
  src/main/java/com/samsamhajo/deepground/report/dto/ReportResponse.java
  src/main/java/com/samsamhajo/deepground/report/entity/Report.java
  src/main/java/com/samsamhajo/deepground/report/enums/AIReviewResult.java
  src/main/java/com/samsamhajo/deepground/report/enums/ReportReason.java
  src/main/java/com/samsamhajo/deepground/report/enums/ReportTargetType.java
  src/main/java/com/samsamhajo/deepground/report/exception/ReportErrorCode.java
  src/main/java/com/samsamhajo/deepground/report/exception/ReportException.java
  src/main/java/com/samsamhajo/deepground/report/repository/ReportRepository.java
  src/main/java/com/samsamhajo/deepground/report/service/ReportPostAIClient.java
  src/main/java/com/samsamhajo/deepground/report/service/ReportService.java
  src/main/java/com/samsamhajo/deepground/report/success/ReportSuccessCode.java
  src/main/resources/application.yml
  src/test/java/com/samsamhajo/deepground/auth/jwt/JwtProviderTest.java
  src/test/java/com/samsamhajo/deepground/auth/service/RefreshAccessTokenTest.java
Labels: feature
