Repository Team-DeepGround/deep-ground-server, pull requests merged in 2025-06, with the labels that each got.

#224 [Feature] 댓글 작성 로직 구현
  src/main/java/com/samsamhajo/deepground/qna/comment/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/comment/controller/CommentController.java
  src/main/java/com/samsamhajo/deepground/qna/comment/dto/CommentCreateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/comment/dto/CommentCreateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/comment/exception/CommentErrorCode.java
  src/main/java/com/samsamhajo/deepground/qna/comment/exception/CommentException.java
  src/main/java/com/samsamhajo/deepground/qna/comment/exception/CommentSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/comment/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/comment/repository/CommentRepository.java
  src/main/java/com/samsamhajo/deepground/qna/comment/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/qna/comment/service/CommentService.java
  src/test/java/com/samsamhajo/deepground/question/CommentTest.java
Labels: feature

#243 [Feature] 댓글 삭제 로직 구현
  src/main/java/com/samsamhajo/deepground/qna/answer/entity/Answer.java
  src/main/java/com/samsamhajo/deepground/qna/comment/controller/CommentController.java
  src/main/java/com/samsamhajo/deepground/qna/comment/dto/CommentCreateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/comment/dto/CommentCreateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/comment/dto/UpdateCommentRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/comment/dto/UpdateCommentResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/comment/exception/CommentErrorCode.java
  src/main/java/com/samsamhajo/deepground/qna/comment/exception/CommentException.java
  src/main/java/com/samsamhajo/deepground/qna/comment/exception/CommentSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/comment/service/CommentService.java
  src/test/java/com/samsamhajo/deepground/question/CommentDeleteTest.java
Labels: feature

#246 [Feature] 답변 미디어 로직 구현
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
  src/main/java/com/samsamhajo/deepground/qna/answer/repository/AnswerMediaRepository.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerMediaService.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
  src/test/java/com/samsamhajo/deepground/question/AnswerMediaTest.java
Labels: feature

#229 [Feature] 댓글에 대한 답글(대댓글) 작성 기능 추가
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupReplyController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupReplyRequest.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupReplyResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupReplyRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupReplyService.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupReplyServiceTest.java
Labels: feature

#222 [Feature] 로그아웃 기능 구현
  src/main/java/com/samsamhajo/deepground/auth/controller/AuthController.java
  src/main/java/com/samsamhajo/deepground/auth/service/AuthService.java
  src/main/java/com/samsamhajo/deepground/auth/success/AuthSuccessCode.java
  src/test/java/com/samsamhajo/deepground/auth/service/LogoutTest.java
Labels: feature

#249 [Feature] 소셜 로그인 기능 구현
  src/main/java/com/samsamhajo/deepground/auth/controller/OAuthController.java
  src/main/java/com/samsamhajo/deepground/auth/oauth/CustomOAuth2UserService.java
  src/main/java/com/samsamhajo/deepground/auth/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/samsamhajo/deepground/auth/oauth/OAuthAttributes.java
  src/main/java/com/samsamhajo/deepground/auth/security/CustomUserDetails.java
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
  src/main/java/com/samsamhajo/deepground/member/entity/Member.java
  src/main/java/com/samsamhajo/deepground/member/repository/MemberRepository.java
  src/main/resources/application.yml
  src/test/java/com/samsamhajo/deepground/auth/oauth/CustomOAuth2UserServiceTest.java
Labels: feature

#226 [Feature] 스터디 스케줄 등록 시 멤버 스터디 스케줄도 자동 등록되도록 기능 추가
  src/main/java/com/samsamhajo/deepground/calendar/entity/MemberStudySchedule.java
  src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
  src/test/java/com/samsamhajo/deepground/calendar/service/MemberStudyScheduleServiceTest.java
  src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java
Labels: feature

#237 [Feature] 피드 답글 좋아요 추가/취소하기
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyLikeController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplySuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyService.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java
Labels: feature

#236 [Feature] 피드 답글 수정하기
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyLikeController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReply.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyMedia.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyException.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplySuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyCreateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyUpdateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyMediaRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyService.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java
Labels: feature

#227 [Feature] 피드 댓글 좋아요 추가/삭제하기
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentLikeController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedCommentLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyLikeController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReply.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyMedia.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyException.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplySuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyCreateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyUpdateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyMediaRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyService.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java
Labels: feature

#225 [Feature] 피드 댓글 수정하기
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentLikeController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedComment.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedCommentLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/model/FeedCommentUpdateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentMediaRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyLikeController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReply.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyMedia.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyException.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplySuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyCreateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyUpdateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyMediaRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyService.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java
Labels: feature

#223 [Feature] 피드 댓글 작성하기
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentLikeController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedComment.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedCommentLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/entity/FeedCommentMedia.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentException.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/model/FeedCommentCreateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/model/FeedCommentUpdateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentMediaRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyLikeController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReply.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyLike.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/entity/FeedReplyMedia.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplyException.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplySuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyCreateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyUpdateRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyMediaRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyService.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java
Labels: feature

#250 [Feature] 채팅 미디어 전송 기능 구현
  src/main/java/com/samsamhajo/deepground/chat/entity/ChatMedia.java
  src/main/java/com/samsamhajo/deepground/chat/exception/ChatMessageErrorCode.java
  src/main/java/com/samsamhajo/deepground/chat/repository/ChatMediaRepository.java
  src/main/java/com/samsamhajo/deepground/chat/service/ChatMessageService.java
  src/test/java/com/samsamhajo/deepground/chat/service/ChatMessageServiceTest.java
Labels: feature

#255 [Feature] 알림 전송 기능을 WebSocket에서 SSE로 변경
  src/main/java/com/samsamhajo/deepground/DeepgroundApplication.java
  src/main/java/com/samsamhajo/deepground/notification/controller/NotificationController.java
  src/main/java/com/samsamhajo/deepground/notification/service/NotificationService.java
  src/main/java/com/samsamhajo/deepground/sse/controller/SseEmitterController.java
  src/main/java/com/samsamhajo/deepground/sse/dto/SseEvent.java
  src/main/java/com/samsamhajo/deepground/sse/dto/SseEventType.java
  src/main/java/com/samsamhajo/deepground/sse/repository/SseEmitterRepository.java
  src/main/java/com/samsamhajo/deepground/sse/repository/SseEmitterRepositoryImpl.java
  src/main/java/com/samsamhajo/deepground/sse/service/SseEmitterService.java
  src/test/java/com/samsamhajo/deepground/notification/service/NotificationServiceTest.java
  src/test/java/com/samsamhajo/deepground/sse/service/SseEmitterServiceTest.java
Labels: feature

#263 [Feature] 채팅 메시지 읽음 기능 구현
  src/main/java/com/samsamhajo/deepground/chat/controller/ChatMessageController.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ReadMessageRequest.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ReadMessageResponse.java
  src/main/java/com/samsamhajo/deepground/chat/dto/UnreadCountResponse.java
  src/main/java/com/samsamhajo/deepground/chat/entity/ChatRoomMember.java
  src/main/java/com/samsamhajo/deepground/chat/exception/ChatMessageErrorCode.java
  src/main/java/com/samsamhajo/deepground/chat/repository/ChatMessageRepository.java
  src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/samsamhajo/deepground/chat/service/ChatMessageService.java
  src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberService.java
  src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomService.java
  src/main/java/com/samsamhajo/deepground/sse/dto/SseEventType.java
  src/test/java/com/samsamhajo/deepground/chat/service/ChatMessageServiceTest.java
Labels: feature

#258 [Feature] 피드 댓글 목록 조회하기
  src/main/java/com/samsamhajo/deepground/feed/feed/controller/FeedController.java
  src/main/java/com/samsamhajo/deepground/feed/feed/exception/FeedSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feed/model/FetchFeedResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feed/model/FetchFeedsResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feed/repository/FeedLikeRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/controller/FeedCommentMediaController.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/exception/FeedCommentSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/model/FeedCommentMediaResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/model/FetchFeedCommentResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/model/FetchFeedCommentsResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/repository/FeedCommentRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/controller/FeedReplyMediaController.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/exception/FeedReplySuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FeedReplyMediaResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FetchFeedRepliesResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/model/FetchFeedReplyResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/repository/FeedReplyRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaService.java
  src/main/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyService.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/controller/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedshared/controller/SharedFeedController.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/dto/SharedFeedRequest.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/exception/SharedFeedErrorCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/exception/SharedFeedException.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/exception/SharedFeedSuccessCode.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/model/FetchSharedFeedResponse.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/repository/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedshared/repository/SharedFeedRepository.java
  src/main/java/com/samsamhajo/deepground/feed/feedshared/service/.gitkeep
  src/main/java/com/samsamhajo/deepground/feed/feedshared/service/SharedFeedService.java
  src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feed/service/FeedServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentMediaServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedcomment/service/FeedCommentServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyLikeServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyMediaServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedreply/service/FeedReplyServiceTest.java
  src/test/java/com/samsamhajo/deepground/feed/feedshared/service/SharedFeedServiceTest.java
Labels: feature

#274 [Refactor]친구 관련 코드 및 회원정보 수정 해 대한 @AuthenticationPrincipal 기반 사용자 ID 처리 리팩토링
  src/main/java/com/samsamhajo/deepground/friend/Dto/FriendRequestDto.java
  src/main/java/com/samsamhajo/deepground/friend/Exception/FriendErrorCode.java
  src/main/java/com/samsamhajo/deepground/friend/controller/FriendController.java
  src/main/java/com/samsamhajo/deepground/friend/repository/FriendRepository.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/main/java/com/samsamhajo/deepground/member/controller/MemberController.java
  src/main/java/com/samsamhajo/deepground/member/exception/MemberErrorCode.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendRequestTest.java
  src/test/java/com/samsamhajo/deepground/Friend/FriendService/FriendsTest.java
Labels: refactor

#276 [Feature] 기술 태그 enum 기반 다중 선택 기능 적용
  src/main/java/com/samsamhajo/deepground/global/config/SecurityConfig.java
  src/main/java/com/samsamhajo/deepground/global/config/SwaggerConfig.java
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCreateRequest.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupCreateResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroup.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/TechTag.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
Labels: feature

#290 [Feature] 스터디장 스터디 수락 기능 구현
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupDetailResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupAcceptService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupMemberQueryService.java
Labels: feature

#292 [Feature] 멤버스터디dto에 studyGroupId 필드 추가
  src/main/java/com/samsamhajo/deepground/calendar/dto/MemberScheduleCalendarResponseDto.java
  src/main/java/com/samsamhajo/deepground/calendar/repository/MemberStudyScheduleRepository.java
Labels: feature

#286 [Feature] 채팅방 목록 조회 기능 구현
  src/main/java/com/samsamhajo/deepground/chat/controller/ChatMessageController.java
  src/main/java/com/samsamhajo/deepground/chat/controller/ChatRoomController.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatRoomInfo.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatRoomInitResponse.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatRoomListResponse.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatRoomResponse.java
  src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomMemberService.java
  src/main/java/com/samsamhajo/deepground/chat/success/ChatSuccessCode.java
Labels: feature

#285 [[Refactor] 질문, 답변, 댓글 관련 @AuthenticationPrincipal 기반 사용자 ID 처리 리팩토링
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerController.java
  src/main/java/com/samsamhajo/deepground/qna/answer/controller/AnswerLikeController.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerCreateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerDetailDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerUpdateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/dto/AnswerUpdateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerErrorCode.java
  src/main/java/com/samsamhajo/deepground/qna/answer/exception/AnswerSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/answer/repository/AnswerRepository.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerMediaService.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerService.java
  src/main/java/com/samsamhajo/deepground/qna/comment/controller/CommentController.java
  src/main/java/com/samsamhajo/deepground/qna/comment/dto/CommentCreateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/comment/service/CommentService.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionCreateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionCreateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionDetailResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionListResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionSummaryDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionUpdateRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionUpdateResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionUpdateStatusRequestDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/Dto/QuestionUpdateStatusResponseDto.java
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionController.java
  src/main/java/com/samsamhajo/deepground/qna/question/controller/QuestionTagController.java
  src/main/java/com/samsamhajo/deepground/qna/question/entity/Question.java
  src/main/java/com/samsamhajo/deepground/qna/question/exception/QuestionSuccessCode.java
  src/main/java/com/samsamhajo/deepground/qna/question/repository/QuestionMediaRepository.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionService.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionTagService.java
  src/test/java/com/samsamhajo/deepground/question/AnswerDeleteTest.java
  src/test/java/com/samsamhajo/deepground/question/AnswerUpdateTest.java
  src/test/java/com/samsamhajo/deepground/question/CommentDeleteTest.java
  src/test/java/com/samsamhajo/deepground/question/CommentUpdateTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionDeleteTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionStatusTest.java
  src/test/java/com/samsamhajo/deepground/question/QuestionUpdateTest.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupAdminViewServiceTest.java
Labels: refactor

#294 [Refactor] StudyGroup의 getMember()를 getCreator()로 변경
  src/main/java/com/samsamhajo/deepground/calendar/service/StudyScheduleService.java
  src/test/java/com/samsamhajo/deepground/calendar/service/StudyScheduleServiceTest.java
Labels: refactor

#305 [Feature] 파일 서버 AWS s3 연동 로직 구현
  build.gradle
  src/main/java/com/samsamhajo/deepground/feed/feed/service/FeedMediaService.java
  src/main/java/com/samsamhajo/deepground/global/config/S3Config.java
  src/main/java/com/samsamhajo/deepground/global/upload/S3Uploader.java
  src/main/java/com/samsamhajo/deepground/global/upload/exception/UploadErrorCode.java
  src/main/java/com/samsamhajo/deepground/global/upload/exception/UploadException.java
  src/main/java/com/samsamhajo/deepground/member/Dto/MemberProfileDto.java
  src/main/java/com/samsamhajo/deepground/member/controller/MemberController.java
  src/main/java/com/samsamhajo/deepground/member/service/MemberService.java
  src/main/java/com/samsamhajo/deepground/qna/answer/service/AnswerMediaService.java
  src/main/java/com/samsamhajo/deepground/qna/question/service/QuestionMediaService.java
  src/main/resources/application.yml
  src/test/java/com/samsamhajo/deepground/member/service/ProfileTest.java
Labels: feature

#308 [Feature] 스터디 참여 상태 분기 로직 및 응답 필드 추가
  src/main/java/com/samsamhajo/deepground/studyGroup/controller/StudyGroupController.java
  src/main/java/com/samsamhajo/deepground/studyGroup/dto/StudyGroupDetailResponse.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroupMemberStatus.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupCommentRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupMemberRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupReplyRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/repository/StudyGroupRepository.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceDetailsTest.java
Labels: refactor

#311 [Feature] 채팅 & 알림 도메인 API 연동
  src/main/java/com/samsamhajo/deepground/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/com/samsamhajo/deepground/chat/controller/ChatMediaController.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatMediaResponse.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatMediaUploadResponse.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatMessageResponse.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatRoomInfo.java
  src/main/java/com/samsamhajo/deepground/chat/dto/ChatRoomResponse.java
  src/main/java/com/samsamhajo/deepground/chat/entity/ChatMessage.java
  src/main/java/com/samsamhajo/deepground/chat/exception/ChatErrorCode.java
  src/main/java/com/samsamhajo/deepground/chat/repository/ChatMediaRepository.java
  src/main/java/com/samsamhajo/deepground/chat/repository/ChatRoomMemberRepository.java
  src/main/java/com/samsamhajo/deepground/chat/service/ChatMediaService.java
  src/main/java/com/samsamhajo/deepground/chat/service/ChatMessageService.java
  src/main/java/com/samsamhajo/deepground/chat/service/ChatRoomService.java
  src/main/java/com/samsamhajo/deepground/friend/service/FriendService.java
  src/main/java/com/samsamhajo/deepground/member/Dto/PresenceDto.java
  src/main/java/com/samsamhajo/deepground/member/controller/MemberController.java
  src/main/java/com/samsamhajo/deepground/member/exception/MemberSuccessCode.java
  src/main/java/com/samsamhajo/deepground/member/repository/PresenceRepository.java
  src/main/java/com/samsamhajo/deepground/member/repository/PresenceRepositoryImpl.java
  src/main/java/com/samsamhajo/deepground/member/service/MemberPresenceService.java
  src/main/java/com/samsamhajo/deepground/member/service/PresenceService.java
  src/main/java/com/samsamhajo/deepground/notification/controller/NotificationController.java
  src/main/java/com/samsamhajo/deepground/notification/dto/NotificationUnreadResponse.java
  src/main/java/com/samsamhajo/deepground/notification/event/NotificationEvent.java
  src/main/java/com/samsamhajo/deepground/notification/repository/NotificationRepository.java
  src/main/java/com/samsamhajo/deepground/notification/service/NotificationEventListener.java
  src/main/java/com/samsamhajo/deepground/notification/service/NotificationService.java
  src/main/java/com/samsamhajo/deepground/notification/success/NotificationSuccessCode.java
  src/main/java/com/samsamhajo/deepground/sse/dto/SseEvent.java
  src/main/java/com/samsamhajo/deepground/sse/dto/SseEventType.java
  src/main/java/com/samsamhajo/deepground/sse/event/SseSubscribeEvent.java
  src/main/java/com/samsamhajo/deepground/sse/event/SseUnsubscribeEvent.java
  src/main/java/com/samsamhajo/deepground/sse/service/SseEmitterService.java
  src/main/java/com/samsamhajo/deepground/sse/service/SseEventListener.java
  src/main/java/com/samsamhajo/deepground/studyGroup/entity/StudyGroup.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupAcceptService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupDeleteService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupKickService.java
  src/main/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupService.java
  src/test/java/com/samsamhajo/deepground/chat/service/ChatMediaServiceTest.java
  src/test/java/com/samsamhajo/deepground/chat/service/ChatMessageServiceTest.java
  src/test/java/com/samsamhajo/deepground/member/service/PresenceServiceTest.java
  src/test/java/com/samsamhajo/deepground/notification/service/NotificationServiceTest.java
  src/test/java/com/samsamhajo/deepground/sse/service/SseEmitterServiceTest.java
  src/test/java/com/samsamhajo/deepground/studyGroup/service/StudyGroupServiceTest.java
Labels: feature, refactor
